name: serge
favicon: null
layout_spectrum: 0.96111
typography_spectrum: 0.14175
title: "Serge Jespers' Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3159924503415823
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
