name: serge
favicon: null
layout_spectrum: 0.850854818476364
typography_spectrum: 0.38371356786228716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3159924503415823
  lightness: 0.9745747575070709
  saturation: 0.12052444275468588
  rhythmicContrast: 0.7951620635576546
purpose: []
